#################### default parameters ################################
# favicon
favicon = "images/fav.png"
# logo
logo = "images/icon.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "170x"
# logo text will only show when logo is missing.
logo_text = "Charles Dpj"
# navbar fixed to top
navbar_fixed = false
# OpenGraph / Twitter Card metadata
description = "I make awesome programming, tech and non-tech related contents, come check it out, I know you'll find it interseting"
author = "Charles Dpj"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
address = "Rivers, Nigeria"
mobile = ""
email = "Charlesdpj78@gmail.com"
# contact form action
contact_form_action = "https://formspree.io/f/mrgwedbz" # contact form works with https://formspree.io
# search
search = true

# Posts related Titles & Contents
categories_title = "Blog Categories"
posts_title = "Featured"
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
featured_post_button = "Featured"
recent_post_button = "Recent"
read_more_button = "Read more"
previous_button = "Previous"
next_button = "Next"
related_posts = "Related Posts"
showing_posts = "Showing Post From"
no_categories_found = "No Categories Found"
no_tags_found = "No Tags Found"

mainSections = ["blog"]
# about widget content
about_widget_content = "I thought the potato picture looked funny. Anyways I'm Charles, I'm a software developer, I work primarily on the backend building infastructures with Go. I'm currently working on something fun right now. I made this blog to share articles, thoughts and for documentating progarmming related stuff. If you're interested in what I do feel free to connect with me"
 
# footer content
footer_content = "Hi, hope you're having a lovely day!"
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""
# copyright
theme_copyright = false
copyright = "Copyright © 2023 Charles Dpj"

# 404
error_404_text = "404 Page Not Found!"
error_404_button = "Back To Home"

# Preloader
[preloader]
enable = false
preloader = "images/gopher.gif" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
title_large = "Welcome **!**"
title_small = "to Charles Dpj's Blog"
image = "images/gopher.png"
background_image = "/images/banner-bg-shape.svg"
content = "Welcome to my blog, I'm Charles a Backend Developer, I'm currently working on software infastructures with Go"
button_label = "Know More"
button_link = "about/"

# Advertise
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "got it"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = true
newsletter_title = "Join Our Newsletter"
newsletter_invitation = "You get updated whenever something new comes up, subcribe, I promise no spam"
_placeholder = "Type And Hit Enter"
newsletter_reminder_a = "You can always unsubcribe whenever you want.By signing up you agree to this"
newsletter_reminder_b = "Privacy Policy"
newsletter_button = "Get me in"
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us21.list-manage.com/subscribe/post?u=b46e79e5f55a39bd35a58dbd8&amp;id=3282287065&amp;f_id=003d63e1f0" # replace this url with yours
mailchimp_form_name = "b_b46e79e5f55a39bd35a58dbd8_3282287065" # replace this code with yours


############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/profile.php?id=100076517981765"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/BunngeeeGum"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.instagram.com/oluwaseundpj/?next=%2Funidosenoracionorg%2F"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/Cprime50"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/in/charles-dpj/"
